Repository HamdyPs/Hamdy-Noor, pull requests merged in 2023-03, with the labels that each got.

#2 make the structure
  index.html
  script.js
  style.css
Labels: good first issue

#5 add html css code
  index.html
  style.css
Labels: approved

#7 adding js code
  index.html
  script.js
Labels: documentation

#9 adding delete function and style
  ,
  index.html
  media.css
  script.js
  style.css
Labels: approved
